### ISSUE TITLE
Process test runs joint errors calculations cannot read qpos & qvel

### ISSUE THREAD

**Issue by sherwin0402** [aikkala/O2MConverter#5]
Thanks for the open source converter. I was following your steps as per Readme and when it reaches the calculate joint errors in process test runs, the format of data is different from your pickle data dump from optimize mujoco parameters. 

From process_test_runs.py calculate_joint_errors_function
```
states = data[run_idx]["states"]
controls = data[run_idx]["controls"]
timestep = data[run_idx]["timestep"]
run = data[run_idx]["run"]
```

From optimize_mujoco_parameters.py collect_data_from_runs function
```
data.append({"qpos": qpos_values, "qvel": qvel_values, "controls": controls.values,
                     "state_names": state_names, "muscle_names": list(controls),
                     "timestep": env.timestep, "success": success, "run": run, "num_evals": num_evals})
```

**Comment by aikkala** [comment]
Hi,

Unfortunately some of the code has diverged from what it used to be. I've pushed some changes into the repo that'll hopefully help with the problem you've encountered.

**Comment by sherwin0402** [comment]
Thanks for the prompt change!
